### Get simple select

POST http://localhost:8080/query
Content-Type: application/json

{
    "query": "SELECT 1"
}

### Get all tables

POST http://localhost:8080/query
Content-Type: application/json

{
    "query": "SELECT * from system.tables;"
}

### Multi-statement script (split + sequential run, shared session)

POST http://localhost:8080/query
Content-Type: application/json

{
    "query": "CREATE TABLE IF NOT EXISTS test_table (id UInt32) ENGINE = Memory;\nINSERT INTO test_table VALUES (1), (2);\nSELECT * FROM test_table"
}
